### ISSUE TITLE
New versions of recently updated apps are not available

### ISSUE THREAD

**Issue by alexkdeveloper** [elementary/appcenter-reviews#416]
Updates are not available for the following applications, although the corresponding pull requests were successfully merged a few days ago:
com.github.alexkdeveloper.guessnumber
com.github.alexkdeveloper.bmi
com.github.alexkdeveloper.pasgen

**Comment by danirabbit** [comment]
Looks like we ran out of space on the server. It was updated last night, so I'll make sure to re-run these :)
