### ISSUE TITLE
Add Document Scanner (GNOME) in AppCenter (and some other utilities)

### ISSUE THREAD

**Issue by Odi-3** [elementary/appcenter-reviews#453]
### Problem

In elementary there aren't some important utilities: e.g. Document Scanner, Disk utility and Maps.
The related Flathub versions do not follow the system GTK4 theme.

### Proposal

I think the first one is the most important and essential, but I invite you to consider the others as well. You could do the same work that has already been done with File Roller, Fonts and Evince.

**Comment by danirabbit** [comment]
Hey thanks for the suggestion. I'm going to close this as "Design conflict" We removed document scanner from the default install a while back. There's a Maps app made for elementary OS in AppCenter already. We only do integration work on apps that are pre-installed, we don't maintain any packages that aren't installed by default
