### ISSUE TITLE
EOL doesn't seem to propagate to Flatpak remote

### ISSUE THREAD

**Issue by cassidyjames** [elementary/appcenter-reviews#484]
### What Happened?

The only examples I see of EOL apps still show their pre-EOL updates in AppCenter, and don't warn when installing or updating from the CLI.

- Dippi
- Clairvoyant
- Principles
- Palette
- LookBook

In all cases, the apps are showing the release information before their respective EOL update in the remote's AppStream data. For example, installing or updating LookBook doesn't recommend installing Icon Browser from the Flatpak CLI, and Clairvoyant is still showing its 2.0.0 release, meaning the 2.0.1 release never made it into the remote.

### Steps to Reproduce

1. Mark an app as EOL in this repo, either with no other updates (like Dippi), with a version bump (like Clairvoyant), or with a rebase (like LookBook).
2. Merge it
3. See that the app's update never comes through to the AppCenter remote, AppStream data, Flatpak CLI, AppCenter native client, or AppCenter website

### Expected Behavior

Marking an app as EOL in this repo should propagate that information to the Flatpak remote.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by davidmhewitt** [comment]
This looks to be a problem in Flatpak's GitHub actions, PR to fix it submitted here: https://github.com/flatpak/flatpak-github-actions/pull/157

Once that's fixed, I'll re-run the publish for your recent EoL'd apps and let you know.

**Comment by cassidyjames** [comment]
Thanks, @davidmhewitt!

**Comment by davidmhewitt** [comment]
Still progressing this, found another issue with the GitHub actions and opened another PR:
https://github.com/flatpak/flatpak-github-actions/pull/160
