### ISSUE TITLE
App submission doesn't result in pull request

### ISSUE THREAD

**Issue by ztefn** [elementary/appcenter-reviews#90]
Yesterday (or 18 hours ago) I created release tag [1.145.0](https://github.com/ztefn/haguichi/releases/tag/1.145.0) and submitted it to the dashboard at https://beta.developer.elementary.io/submissions. I got a message that my app has been submitted for review and will appear as a pull request in the review queue shortly.

On the dashboard itself a section called _Recent Apps_ appeared listing a generic app icon without any info and only a label saying _Processing Releasing_:
![Screenshot from 2021-08-21 10-11-18](https://user-images.githubusercontent.com/343442/130315495-3f616da9-04a5-434a-8890-e2c37e356458.png)

After a few hours the _Recent Apps_ listing was gone and no pull request was ever created... no feedback, nothing.

**Comment by ryonakano** [comment]
The new AppCenter Dashboard is still under development [here](https://github.com/elementary/appcenter-dashboard) so we need to create Pull Requests manually for now.

**Comment by ztefn** [comment]
Under development? Last commit for appcenter-dashboard was 21 days ago...

**Comment by cassidyjames** [comment]
@ztefn yes, currently the Dashboard work is all volunteer and we've been a bit busy with the actual release. We've also been working on the backend and the automation bits of the submission process itself. I have it on my list of things to do to update the README here and possibly the dashboard itself to better reflect reality, but at the moment you can file a PR here to submit your app.

**Comment by ztefn** [comment]
Opened #98
